version: "3"

services:
  database_wongames:
    image: postgres
    container_name: database_wongames
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wongames
      - POSTGRES_PASSWORD=wongames
      - POSTGRES_DB=wongames
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
